katla:
  name: katla
  chainId: 167008
  domainId: 167008
  protocol: ethereum
  rpcUrls:
    - http: https://rpc.katla.taiko.xyz
  nativeToken:
    name: Eth # String
    symbol: ETH # String
    decimals: 18 # Number
opti:
  name: opti
  chainId: 11155420
  domainId: 11155420
  protocol: ethereum
  rpcUrls:
    - http: https://sepolia.optimism.io
arbisep:
  name: arbisep
  chainId: 421614
  domainId: 421614
  protocol: ethereum
  rpcUrls:
    - http: https://sepolia-rollup.arbitrum.io/rpc

